backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "livres"
    label: "Livres"
    folder: "_livres"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Genre", name: "genre", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
